### ISSUE TITLE
Consistently handle optional dependency import errors

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#118]
Often, when importing an optional dependency, a try, catch, except, pass is used. It would be nice if there was a wrapper to warn the user that a dependency is not installed, or just not wrap the import at all and let it crash to make it more obvious what the problem is.

**Comment by tyarkoni** [comment]
To elaborate on this (looping @andrewheusser in), I think the pattern we want here is to mark each optional dependency required for a particular `Transformer` with a boolean flag (e.g., `has_google`) at the top of the module, and then check that flag inside the relevant `transform` call. In many cases it's only one `Transformer` within a module that has a dependency, so we don't want to just throw errors at the top of the module; they should be re-raised only when the dependency in question needs to be invoked (we could potentially raise a warning at the top though, along the lines of "warning: you will not be able to call any Transformers that require ...").

Since this is going to happen in a whole bunch of places, it may also make sense to abstract both the optional importing and the flag checking code into a couple of small functions and put them in the `utils.py` module.

**Comment by andrewheusser** [comment]
👍 thanks for the explanation, makes sense.  i'd be happy to help!  I've also got some thoughts on useful filters (e.g. downsampling images) and transformers (text to topic model). Do you have something set up for discussion, like gitter, or should I post as issues for feedback?

**Comment by tyarkoni** [comment]
Just created a [gitter channel](https://gitter.im/pythonpliers), but I generally prefer to use github issues for discussion. Adding some new filters and transformers would be great, and both of those ideas sound very useful. Feel free to open issues for discussion.
