### ISSUE TITLE
Add more "resolutions" for IBM transcription

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#150]
PR #147 added the ability to split up text by phrases (i.e. periods). It would be nice to support arbitrary resolutions (e.g. bigrams, etc...)

**Comment by tyarkoni** [comment]
I don't really see a common use case for this, so I'm closing it. If we were going to go down this road, we would probably want to implement a generic `TextSplittingFilter` that operates on `TextStim`s, rather than doing this in the IBM speech-to-text extractor. But that also seems like an edge case, so I don't think we need to support this until someone asks for it.
