### ISSUE TITLE
Indico API 1.0 will be deprecated 4/1/2018

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#275]
Looks like pliers still uses API 1? I have a vague recollection of upgrading the API but I just received a warning about it.

**Comment by tyarkoni** [comment]
Unrelated, but just FYI, I haven't raised the limit yet

**Comment by qmac** [comment]
What version of `indicoio` do you have installed? It would be weird if their client library wasn't interfacing with the most recent version, and I don't see any warning with my version.

**Comment by qmac** [comment]
Running into any problems with this?

**Comment by adelavega** [comment]
I haven't been using Indico, so I wouldn't know, but I bet its broken.

**Comment by qmac** [comment]
Welp, nothing's broken. I'm going to close this and chalk it up to something funky happening on their backend, or maybe they are just always sending back the warning regardless of the requested version. I am 100% confident that we are querying `https://apiv2.indico.io/fer/batch`.

That being said, I guess we can't be certain that the [python CLI](https://github.com/IndicoDataSolutions/IndicoIo-python) is up to date, as its been ~9 months since the last push to PyPI.
