### ISSUE TITLE
Stim properties used for hashing are not uniquely identifying

### ISSUE THREAD

**Issue by adelavega** [tyarkoni/pliers#293]
There seems to be a weird issue with caching (I'm guessing) in the `ComplexTextExtractor`

Take for instance:

```
ext = ComplexTextExtractor()
stims = [ComplexTextStim(text='hello'), ComplexTextStim(text='different!')]
res = ext.transform(stims)
[r._data for r in res]
Out[13]: [['hello'], ['hello']]
```

Basically, it outputs the same word, although more than one was passed in

**Comment by qmac** [comment]
Yeah this looks like an issue with caching not being content-aware. I suspect this is also an issue with `ImageStim`s initialized from `data` rather than a file. The only reason it's not an issue for normal `TextStim`s is because we insert the `data` into the `name` (which is used for caching).

@tyarkoni thoughts on a solution? we could omit caching when `filename` is undefined?

**Comment by tyarkoni** [comment]
Probably the right thing to do would be to hash based on contents rather than filename (or to use both). One thing we could do is, in the base `Stim.__hash__` method, instead of automatically including `self.filename` and `self.name` in the hash, we could instead include a property called `_hash_contents`, which would default to those two properties, but could be overwritten in subclasses. For `ComplexTextStim`, we could then use `text` instead of `name`. For `ImageStim`, we could eventually include a hash of the image data (though I'd be fine with just fixing `ComplexTextStim` in the short term).

**Comment by adelavega** [comment]
Yeah for what it's worth, I don't think it should be expensive to hash even large stimuli. For example, hashing a video stimulus (Merlin clip) using a blocksize of 65536 bytes (and updating the hash  for every block), only takes a few seconds on my computer.
