### ISSUE TITLE
WordEmbeddingExtractor returning same object

### ISSUE THREAD

**Issue by debanjanghosh** [tyarkoni/pliers#310]
I did this,
raw1 = "these are the favorite things"
raw2 = "this is nice"

text1 = ComplexTextStim(text=raw1)
text2 = ComplexTextStim(text=raw2)

ext = WordEmbeddingExtractor(embedding_file) 
embed1 = ext.transform(text1)
embed2 = ext.transform(text2)

However, it seems that the embed1 and embed2 are identical objects here (both contain raw1).

**Comment by qmac** [comment]
Sorry but I cannot seem to recreate this issue. Since you are passing in ComplexTextStim, the output should be lists of ExtractorResults. Is this the case? Embed1 should have 5 ExtractorResults and the list from embed2 should have 3.

As a check, can you see if disabling caching before running those commands fixes this? This can be done via:
```
from pliers import config
config.set_option('cache_transformers', False)
```

**Comment by debanjanghosh** [comment]
Thanks, setting the 'cache_transformers' to False worked!

**Comment by qmac** [comment]
Hey @debanjanghosh were you using pliers installed from PyPi? Just checking because we had a fix for this caching bug that is in `master` but hasn't been released to PyPi. @tyarkoni might be a good idea to push a release?

**Comment by debanjanghosh** [comment]
No, I did "pip install pliers".
