### ISSUE TITLE
Implement new _transform methods in BatchTransformerMixins

### ISSUE THREAD

**Issue by qmac** [tyarkoni/pliers#72]
Now that we have added the functionality thanks to #69 we should implement batch processing for transformers that can gain from it. This includes a fair chunk of the API and Google transformers.

**Comment by tyarkoni** [comment]
Per discussion, closing this for now because it's not clear that batch-processing images within API `Extractor`s is going to provide enough benefit to warrant the time investment. Most APIs charge on a per-file basis, so sending multiple files will, at best, save some (but probably not much) overhead on the request and response.

**Comment by qmac** [comment]
Reopening because found notable performance differences for the Clarifai API
